export const LOGIN_USER = "login_user"
export const REGISTER_USER = "register_user"
export const AUTH_USER = "auth_user"
export const CREATE_BOARD = "create_board"
export const BOARD_LIST = "board_list"
export const BOARD_DETAIL = "board_detail"
export const UPDATE_BOARD = "update_board"
export const DELETE_BOARD = "delete_board"