export const LOGIN_USER = "login_user"
export const REGISTER_USER = "register_user"
export const AUTH_USER = "auth_user"
// export const AUTH_USER_UPDATE = "auth_user_update"
export const FOLLOW_LENGTH = "follow_length"
//board
export const CREATE_BOARD = "create_board"
export const BOARD_LIST = "board_list"
export const BOARD_DETAIL = "board_detail"
export const UPDATE_BOARD = "update_board"
export const DELETE_BOARD = "delete_board"
export const RECCOMAND_LIST = "reccomand_list"
//chat
export const SEND_CHAT = "send_chat"
export const RECEIVE_CHAT = "receive_chat"
export const CHAT_LIST = "chat_list"
export const CREATE_CHAT = "create_chat"
export const CHAT_DETAIL = "chat_detail"
export const CHAT_REFRESH = "chat_refresh"